### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by Dimokus88** [Dimokus88/Tasks#1]
Tasks list:
- [ ] [Optimism RPC node on Akash](/Dimokus88/Tasks/issues/2) (Stastus: Creating a custom deployment script.)
- [ ] [Arbitrum RPC node on Akash Network](/Dimokus88/Tasks/issues/3) (Status: Create technical guide)
- [ ]  [Run POKT rpc nodes](/Dimokus88/Tasks/issues/4) and have a few simultaneous deployments, but one of those deployments running Cherry Servers' provider to understand the cost for a week.
- [ ] Telegram: Kalagato - connected you with their team on TG.  We'll need to help them spin up their VPN on Akash for them to do some internal testing on their side.
- [ ] Could you run few nodes from Cosmos omnibus, preferrably Osmosis, Cosmos, Akash and maybe Kava on Cherry Servers to and get the cost / reliability for a week.
- [ ] Lastly, could you dockerize this VPN to add to awesome-akash, have a deployment guide and run it on akash for a week?  I'd like to understand what the cost is to benchmark against these cloud providers listed here: https://en.amnezia.org/instruction.html.  Source (https://www.wired.com/story/amnezia-vpn-russia-censorship)
